# Generated by Django 4.2.3 on 2023-07-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTelovendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
