# Generated by Django 4.2.3 on 2023-07-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTelovendo', '0002_proveedor_email_proveedor_productos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
